nventive/NuGet.Updater

- gitversion.yml
- src/NuGet.Updater.sln
> Changed gitversion mode to mainline

- src/NuGet.Updater.Tool/Program.cs
Bug fix
Help was always showing up
Help is now only showing up when adequate
> Fixed detection of no parameters set

- src/NuGet.Updater/Extensions/UpdateTargetExtensions.cs
- src/NuGet.Updater/Extensions/UpdaterParametersExtension.cs
- src/NuGet.Updater/Helpers/FileHelper.cs
Feature
Some parameters are not correctly written in the summary
All parameters are now properly displayed in the summary
> Added more information in the summary

- src/NuGet.Updater/Log/SimpleTextWriter.cs
Bug fix
SimpleTextWriter only implements Write, when the Logger uses WriteLine
SimpleTextWriter now implements WriteLine
> Ensured SimpleTextWriter implements WriteLine

- src/NuGet.Updater.Tool/Program.cs
- src/NuGet.Updater.Tool/Properties/launchSettings.json
Code style update (formatting)
The "allowDowngrade" parameter requires a value.
The "allowDowngrade" parameter doesn't require a value. It will be true when set
> Simplified the downgrade parameter in the tool

- CHANGELOG.md
- src/NuGet.Updater/Entities/UpdateTarget.cs
- src/NuGet.Updater/Extensions/UpdateTargetExtensions.cs
- src/NuGet.Updater/Helpers/FileHelper.Net.cs
- src/NuGet.Updater/Helpers/FileHelper.UAP.cs
- src/NuGet.Updater/Helpers/SolutionHelper.cs
- src/NuGet.Updater/NuGetUpdater.cs
Removed references to project.json
Feature 
Only sln files are supported
Folders are now also supported
> Added support for either folder on solution

- src/NuGet.Updater/Extensions/XmlDocumentExtensions.cs
- src/NuGet.Updater/NuGetUpdater.cs
Bug fix 
XML node selection isn't working properly
XML node are correctly selected
> Fixed xml node selection

- CHANGELOG.md
- README.md
- src/NuGet.Updater.Tests/Entities/TestPackageSource.cs
- src/NuGet.Updater.Tests/NuGetUpdaterTests.cs
- src/NuGet.Updater.Tool/Program.cs
- src/NuGet.Updater.Tool/Properties/launchSettings.json
- src/NuGet.Updater/Entities/IUpdaterSource.cs
- src/NuGet.Updater/Entities/UpdaterParameters.cs
- src/NuGet.Updater/Entities/UpdaterSource.cs
- src/NuGet.Updater/Extensions/UpdaterParametersExtension.cs
- src/NuGet.Updater/NuGetUpdater.cs
Feature 
Sources that can be passed are limited to NuGet.org and any number of private sources.
Sources handling has been simplified and any number of public sources can be specified
> Updated sources handling

- CHANGELOG.md
- README.md
- src/NuGet.Updater.Tool/Program.cs
Feature
Documentation content changes
Documentation is missing sample commands. Running the tool without a solution root throws an error.
Documentation contains sample commands. Running the tool without a solution root defaults to the current directory.
> Added sample commands in the documentation

- src/NuGet.Updater/Extensions/PackageSourceExtensions.cs
- src/NuGet.Updater/Extensions/UpdaterParametersExtension.cs
- src/NuGet.Updater/NuGetUpdater.cs
Feature
Packages are all retrieved, even if ignored, one source at a time
Packages are retrieved from all sources in parallel and only if they need to be updated
> Improved package retrieval

- CHANGELOG.md
- src/NuGet.Updater.Tool/Program.cs
- src/NuGet.Updater/Entities/UpdaterParameters.cs
> Mapped the Strict parameter to the tool

- CHANGELOG.md
Documentation content
Changelog doesn't mention new release
Changelog mentions new release
> Updated changelog for version 1.0

- CHANGELOG.md
> Merging back release 1.0 change

- CHANGELOG.md
- src/NuGet.Shared/Helpers/MarkdownHelper.cs
- src/NuGet.Shared/Helpers/StringHelper.cs
- src/NuGet.Shared/NuGet.Shared.projitems
- src/NuGet.Updater/Entities/UpdateResult.cs
- src/NuGet.Updater/Entities/UpdaterParameters.cs
- src/NuGet.Updater/Extensions/UpdateOperationExtensions.cs
- src/NuGet.Updater/Extensions/UpdaterParametersExtension.cs
- src/NuGet.Updater/Log/UpdaterLogger.cs
Refactoring (no functional changes, no api changes) 
Output has been improved
> Improved output of the nuget updater

- CHANGELOG.md
- src/NuGet.Shared/Extensions/XmlDocumentExtensions.cs
- src/NuGet.Shared/Helpers/SolutionHelper.cs
Bug fix
Multiple references of the same package in a nuspec causes the updater to fail
Multiple references of the same package in a nuspec are gracefully handled.
> Ensured multiple package version per file are handled properly

- CHANGELOG.md
- src/NuGet.Shared/Extensions/XmlDocumentExtensions.cs
Bug fix
Versions found in files are assumed to be correct
Versions found in files are now parsed beforehand.
> Adding parsing of the versions

- CHANGELOG.md
- src/NuGet.Shared/Entities/PackageFeed.cs
Bug fix
The author filter is used on both the private and public feeds.
Author filter is now ignored for private sources
> Package author is now ignore for private feeds

- src/NuGet.Shared/Entities/PackageFeed.cs
Bug fix
Private feeds are considered public and vice-versa
Private feeds are now properly considered as private
> Fixed IsPrivate condition

- src/NuGet.Shared/Entities/PackageFeed.cs
- src/NuGet.Updater.Tests/ConsoleArgsParserTests.cs
- src/NuGet.Updater.Tests/NuGet.Updater.Tests.csproj
- src/NuGet.Updater.Tests/Resources/version_overrides.json
- src/NuGet.Updater.Tests/SolutionHelperTests.cs
- src/NuGet.Updater.Tool/Arguments/ConsoleArgError.cs
- src/NuGet.Updater.Tool/Arguments/ConsoleArgErrorType.cs
- src/NuGet.Updater.Tool/Arguments/ConsoleArgsContext.Properties.cs
- src/NuGet.Updater.Tool/Arguments/ConsoleArgsContext.cs
- src/NuGet.Updater.Tool/ConsoleArgsParser.cs
- src/NuGet.Updater.Tool/NuGet.Updater.Tool.csproj
- src/NuGet.Updater.Tool/Program.cs
GitHub Issue: #n/a
- Bug fix
- Refactoring (no functional changes, no api changes)
- Other, please describe: Unit Tests
CLI parameters are not unit-testable and unit-tested.
CLI parameters are now unit-testable and unit-tested.
> unit tests for cli parameters

- .azure-pipelines.yml
Build or CI related changes
NuGet packages are only generated if the individual projects set the GeneratePackageOnBuild variable
The variable is set by the build definition
> Forced package creation
